"""add world_boss tables

Revision ID: 020b6972cfea
Revises: da74ebe4c58e
Create Date: 2026-05-10 00:10:23.969109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020b6972cfea'
down_revision: Union[str, None] = 'da74ebe4c58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_bosses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('max_hp', sa.BigInteger(), nullable=False),
    sa.Column('current_hp', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.Column('spawn_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('despawn_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('killed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_boss_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('boss_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('total_damage', sa.BigInteger(), nullable=True),
    sa.Column('last_attack_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reward_claimed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['boss_id'], ['world_bosses.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('world_boss_participants')
    op.drop_table('world_bosses')
    # ### end Alembic commands ###
