"""create users and characters tables

Revision ID: 38e6b2b94b98
Revises: 
Create Date: 2026-05-09 19:17:24.409393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e6b2b94b98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('class_id', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('soul_level', sa.Integer(), nullable=True),
    sa.Column('current_exp', sa.BigInteger(), nullable=True),
    sa.Column('gold', sa.BigInteger(), nullable=True),
    sa.Column('gems', sa.Integer(), nullable=True),
    sa.Column('current_map_id', sa.Integer(), nullable=True),
    sa.Column('last_logout_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('last_afk_claim_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('legendary_pity_counter', sa.Integer(), nullable=True),
    sa.Column('mythic_pity_counter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    op.drop_table('users')
    # ### end Alembic commands ###
